general:
    labels: /data/tedlium2-xnmt/bpe300/units.json
    logfile: bpe300D.log
    final_dump: bpe300D.mdl
    epochs: 50
    learning_rate: 0.0005
    momentum: 0.9
    max_norm: 400
    use_cuda: True
    optimizer: optimizer.SGD
    # model_params: /project/iwslt2015/EN/LM-tests/pytorch_ctc/egs/tedlium/train2/bpe0D.mdl
    # remove_params: module.linear.weight

# Define the datasets
data:
    # Common settings apply to all datasets, but can be overwritten per data set
    common:
        input_dim: 80
        collate_fn: data_loader.collate.collate_3D
        context: 1
        step_size: 3
        batch_size: 10
        num_workers: 1
        feat_length_min: 100
        feat_length_max: 3500
        target_length_max: 630
        frame_shift: 0.010
    train:
        data_set: data_loader.iwslt_data_loader.SequenceDataset
        data_loader: data_loader.iwslt_data_loader.AudioDataLoader
        audio_features: /data/tedlium2-xnmt/feat/train.h5
        input_text: /data/tedlium2-xnmt/bpe300/train.units
        shuffle: True
    valid:
        data_set: data_loader.iwslt_data_loader.SequenceDataset
        data_loader: data_loader.iwslt_data_loader.AudioDataLoader
        audio_features: /data/tedlium2-xnmt/feat/dev.h5
        input_text: /data/tedlium2-xnmt/bpe300/dev.units
        start_idx: 1

# Define the model and the parameters
# Each model may support custom parameters
model:
    class: model.simpleLSTM.LSTM
    rnn_hidden_size: 400
    rnn_layers: 4
    bidirectional: True
    dropout: 0.25
